name: CI/CD for aiassistant App

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the repository
    - name: Check out the repo
      uses: actions/checkout@v2
    
    # Step 2: Set up Docker Buildx (optional, but useful for multi-arch)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # Step 3: Log in to DockerHub (replace with your DockerHub username and password)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./DockerFile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/synthetic-financial-data:latest
    
